import "../app/app.css";

export const metadata = {
  title: "Portafolio",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?=4"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
